version: '3.8'

services:
  mongodb:
    image: mongo:8.2
    container_name: mongo-db-local
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network-local
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18.1
    container_name: postgres-db-local
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata-local:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - app-network-local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin-local
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5051:80
    networks:
      - app-network-local

networks:
  app-network-local:
    driver: bridge

volumes:
  pgdata-local:
