services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    image: repo-pipeline:latest
    container_name: jobmarket_pipeline
    env_file:
      - .env
    volumes:
      - type: bind
        source: ../data
        target: /app/data
    command: ["python", "-m", "src.data.main"]
    restart: "no"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    image: repo-ui:latest
    container_name: jobmarket_ui
    env_file:
      - .env
    volumes:
      - type: bind
        source: ../data
        target: /app/data
    ports:
      - "127.0.0.1:8501:8501"
    command: ["python", "-m", "streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]
    depends_on:
      - pipeline
    profiles: ["ui"]
